name: "PyInstaller ManyLinux Docker Action"
description: "Run Pyinstaller on ManyLinux (x86_64)"
branding:
  icon: "box"
  color: "green"
inputs:
  pyinstaller-params:
    description: "List of parameters for pyinstaller"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/sede-open/pyinstaller-manylinux:latest"
  args:
    - ${{ fromJSON(inputs.pyinstaller-params) }}
